"""Warehouse robotics page."""

from __future__ import annotations

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

from src.app.ui import apply_page_config, get_pipeline_data, metric_panel, render_header, render_sidebar, style_plotly
from src.simulation.robot import RobotStatus
from src.simulation.simulator import WarehouseSimulator
from src.simulation.warehouse import Cell

apply_page_config("Warehouse Robotics")
data = get_pipeline_data()
render_sidebar("robotics", data)

with st.sidebar:
    st.divider()
    n_robots = st.slider("Robots", 1, 8, data["config"]["simulation"]["n_robots"])
    steps = st.slider("Simulation steps", 60, 240, data["config"]["simulation"]["time_steps"], step=20)
    load_factor = st.slider("Load factor", 0.2, 1.8, 1.0, step=0.1)
    rerun = st.button("Run simulation", use_container_width=True, type="primary")


@st.cache_data(show_spinner="Simulating warehouse execution...")
def run_simulation(robot_count: int, sim_steps: int, factor: float):
    config = data["config"].copy()
    config["simulation"] = dict(config["simulation"])
    config["simulation"]["n_robots"] = robot_count
    config["simulation"]["time_steps"] = sim_steps
    config["simulation"]["orders_per_step"] = config["simulation"]["orders_per_step"] * factor
    simulator = WarehouseSimulator(
        config,
        forecast_df=data["future_df"],
        inventory_df=data["inventory_df"],
        slotting_df=data["slotting_df"],
    ).run()
    return {
        "metrics": simulator.get_metrics(),
        "paths": simulator.get_robot_paths_df(),
        "congestion": simulator.get_congestion_df(),
        "tasks": simulator.get_task_log(),
        "grid": simulator.warehouse.to_numpy(),
        "history": simulator.history,
    }


if rerun or "robotics_result" not in st.session_state:
    st.session_state["robotics_result"] = run_simulation(n_robots, steps, load_factor)

result = st.session_state["robotics_result"]
metrics = result["metrics"]
tasks = result["tasks"]
congestion = result["congestion"]
grid = result["grid"]
history = result["history"]

render_header(
    "Simulation Control",
    "Warehouse Robotics",
    "Demand-weighted tasks now drive warehouse traffic. Congestion, queueing, and fulfilment delay are generated by forecast intensity, slotting concentration, and shortage-linked recovery time.",
)

st.markdown(
    f"""
    <div class="panel panel-hero" style="margin-bottom:1.35rem;">
        <div class="page-kicker" style="margin-bottom:0.35rem;">Execution Synopsis</div>
        <div style="display:flex; justify-content:space-between; gap:1.5rem; align-items:end;">
            <div>
                <div style="font-family:'Space Grotesk',sans-serif; font-size:1.95rem; font-weight:700; color:#f4f6ff; line-height:1.06;">
                    {metrics['tasks_generated']} pick tasks generated with {metrics['fulfilment_rate']:.1f}% completion under current labor capacity.
                </div>
                <div class="page-subtitle" style="margin-top:0.65rem; margin-bottom:0;">
                    Queue delay sits at {metrics['avg_queue_delay']:.1f} steps. {metrics['inventory_linked_delays']} tasks inherited shortage friction from upstream inventory risk.
                </div>
            </div>
            <div style="min-width:250px;">
                <div class="security-pill">Robots {n_robots} // Load {load_factor:.1f}x</div>
                <div class="page-meta-bottom" style="margin-top:0.65rem;">Active zones {metrics['zone_task_mix']}</div>
            </div>
        </div>
    </div>
    """,
    unsafe_allow_html=True,
)

for col, html in zip(
    st.columns(5),
    [
        metric_panel("Tasks Generated", f"{metrics['tasks_generated']}", "Forecast-weighted picks created"),
        metric_panel("Fulfilment Rate", f"{metrics['fulfilment_rate']:.1f}%", "Completed versus generated"),
        metric_panel("Lead Time", f"{metrics['avg_fulfilment_time']:.1f}", "Average fulfilment steps"),
        metric_panel("Queue Delay", f"{metrics['avg_queue_delay']:.1f}", "Waiting time before dispatch"),
        metric_panel("Inventory Delays", f"{metrics['inventory_linked_delays']}", "Shortage-linked execution drag"),
    ],
):
    with col:
        st.markdown(html, unsafe_allow_html=True)

left, right = st.columns([1.7, 0.95], gap="large")
with left:
    step = st.slider("Playback step", 0, max(len(history) - 1, 0), min(20, max(len(history) - 1, 0)))
    fig = go.Figure()
    background = np.where(grid == Cell.SHELF, 0.82, np.where(grid == Cell.PACKING, 0.46, 0.05))
    fig.add_trace(
        go.Heatmap(
            z=background,
            colorscale=[[0, "#050a12"], [0.18, "#0a1425"], [0.5, "#0d1c33"], [1, "#13274c"]],
            showscale=False,
            xgap=1,
            ygap=1,
        )
    )
    color_map = {
        RobotStatus.IDLE.name: "#99a8c9",
        RobotStatus.MOVING_TO_SHELF.name: "#a39afc",
        RobotStatus.PICKING.name: "#f6c787",
        RobotStatus.MOVING_TO_PACKING.name: "#8bd7bd",
        RobotStatus.DELIVERING.name: "#f3efff",
        RobotStatus.DELAYED.name: "#ff8d9f",
    }
    if history:
        for snap in history[step]:
            fig.add_trace(
                go.Scatter(
                    x=[snap["col"]],
                    y=[snap["row"]],
                    mode="markers+text",
                    text=[f"R{snap['robot_id']}"],
                    textposition="middle center",
                    textfont=dict(color="#09111f", size=10, family="IBM Plex Mono"),
                    marker=dict(
                        size=16,
                        color=color_map.get(snap["status"], "#f3efff"),
                        line=dict(color="#eef2ff", width=1.2),
                        symbol="circle",
                    ),
                    showlegend=False,
                )
            )
    fig = style_plotly(fig, 520)
    fig.update_layout(
        yaxis=dict(scaleanchor="x", autorange="reversed", showticklabels=False),
        xaxis=dict(showticklabels=False),
    )
    st.markdown('<div class="panel">', unsafe_allow_html=True)
    st.subheader("Warehouse Grid")
    st.caption("Zone congestion now emerges from demand-weighted pick generation and shared aisle access.")
    st.plotly_chart(fig, use_container_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

    if not tasks.empty:
        zone = tasks.groupby("zone").size().rename("tasks").reset_index()
        zone_fig = px.bar(zone, x="zone", y="tasks", color="zone", color_discrete_map={"A": "#a39afc", "B": "#8bd7bd", "C": "#f6c787"})
        zone_fig = style_plotly(zone_fig, 280)
        zone_fig.update_layout(showlegend=False, xaxis_title="Zone", yaxis_title="Task count")
        st.markdown('<div class="panel">', unsafe_allow_html=True)
        st.subheader("Zone Throughput")
        st.plotly_chart(zone_fig, use_container_width=True)
        st.markdown("</div>", unsafe_allow_html=True)

with right:
    heat = congestion.pivot(index="row", columns="col", values="visits").fillna(0)
    heatmap = px.imshow(heat, color_continuous_scale=["#09111f", "#16284b", "#5f63d8", "#f2efff"], aspect="equal")
    heatmap = style_plotly(heatmap, 280)
    st.markdown('<div class="panel">', unsafe_allow_html=True)
    st.subheader("Congestion Index")
    st.plotly_chart(heatmap, use_container_width=True)
    st.markdown("</div>", unsafe_allow_html=True)

    st.markdown('<div class="panel">', unsafe_allow_html=True)
    st.subheader("System Legend")
    st.markdown(
        """
        <div class="note"><span class="tag">Active</span>Robot is moving or delivering.</div>
        <div class="note" style="margin-top:0.7rem;"><span class="tag">Idle</span>Unit is available but currently unassigned.</div>
        <div class="note" style="margin-top:0.7rem;"><span class="tag">Delayed</span>Task inherited shortage-linked recovery time.</div>
        """,
        unsafe_allow_html=True,
    )
    st.markdown("</div>", unsafe_allow_html=True)

    st.markdown('<div class="panel">', unsafe_allow_html=True)
    st.subheader("Fulfilment Queue")
    if not tasks.empty:
        focus = tasks.sort_values(["shortage_delay", "queue_delay"], ascending=[False, False]).head(6)
        for _, row in focus.iterrows():
            st.markdown(
                f"<div class='note' style='margin-bottom:0.78rem;'><span class='tag'>{row['sku']}</span>"
                f"Zone {row['zone']} // Priority {row['priority']:.1f} // Queue {row['queue_delay']} // Shortage {row['shortage_delay']}</div>",
                unsafe_allow_html=True,
            )
    else:
        st.markdown("<div class='note'>No task activity captured.</div>", unsafe_allow_html=True)
    st.markdown("</div>", unsafe_allow_html=True)

bottom_left, bottom_right = st.columns([1.1, 1.3], gap="large")
with bottom_left:
    st.markdown('<div class="panel">', unsafe_allow_html=True)
    st.subheader("Robot State Snapshot")
    if history:
        st.dataframe(pd.DataFrame(history[step]), use_container_width=True, hide_index=True, height=310)
    st.markdown("</div>", unsafe_allow_html=True)

with bottom_right:
    if not tasks.empty:
        queue_fig = px.scatter(
            tasks,
            x="queue_delay",
            y="total_time",
            color="zone",
            size="priority",
            color_discrete_map={"A": "#a39afc", "B": "#8bd7bd", "C": "#f6c787"},
            hover_data=["sku", "shortage_delay"],
        )
        queue_fig = style_plotly(queue_fig, 310)
        queue_fig.update_layout(xaxis_title="Queue delay", yaxis_title="Total fulfilment time")
        st.markdown('<div class="panel">', unsafe_allow_html=True)
        st.subheader("Queue vs Fulfilment Time")
        st.plotly_chart(queue_fig, use_container_width=True)
        st.markdown("</div>", unsafe_allow_html=True)
